### ISSUE TITLE
Large CPU usage increase with Java 21

### ISSUE THREAD

**Issue by MichaelPluessErni** [vaadin/kubernetes-kit#182]
When switching from Java 17 to Java 21 we noticed a big increase in CPU usage on our Google Cloud instances.

<img width="1015" alt="Image" src="https://github.com/user-attachments/assets/fd91bb80-3acc-45fa-8663-f09df5c699a2" />
<img width="1015" alt="Image" src="https://github.com/user-attachments/assets/93b8b714-608d-4102-a0bb-4fe1f606bc77" />

The increased usage disappeared again when we disabled the Kubernetes Kit.

Apparently, the serialization process of the Kubernetes Kit uses much more computing power with Java 21 than with Java 17.

The versions we are using:

spring-boot: 3.4.4
vaadin: 24.6.7
kubernetes-kit-starter: 2.4.1
kubernetes: 1.31

**Comment by mcollovati** [comment]
@MichaelPluessErni do you have any particular JVM settings, for example for garbage collection?

**Comment by MichaelPluessErni** [comment]
@mcollovati We did have them. But we removed those and it made no difference:
`"application.JDK_JAVA_OPTIONS": "\"-XX:+UnlockExperimentalVMOptions -XX:InitiatingHeapOccupancyPercent=30 -XX:G1MixedGCLiveThresholdPercent=85 -XX:G1OldCSetRegionThresholdPercent=25\""`

**Comment by gtzluis** [comment]
are you by any chance using JDK 21.0.3 or earlier? there was an issue with garbage collection, addressed in JDK 21.0.4.
https://bugs.openjdk.org/browse/JDK-8333832

**Comment by MichaelPluessErni** [comment]
Hi Luis

We have version 21.0.6 of Java Temurin running on our pods. The issue persists.

openjdk version "21.0.6" 2025-01-21 LTS
OpenJDK Runtime Environment Temurin-21.0.6+7 (build 21.0.6+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.6+7 (build 21.0.6+7-LTS, mixed mode, sharing)

**Comment by MichaelPluessErni** [comment]
We tried disabling the Kubernetes Kit and the CPU limit utilization went back to pre-Java 21 levels:

![Image](https://github.com/user-attachments/assets/83f276fa-990b-4d22-8859-be9c04f87040)

(Kubernetes Kit disabled on night from 29. to 30. April)
This confirms that the utilization increase originates from the interaction between the Kubernetes Kit and Java 21.

**Comment by mcollovati** [comment]
I did some tests locally (Redis backend), but I cannot see any difference in terms of CPU usage between 17 and 21.
No peaks, even if I quickly scroll up and down a Grid.
